Support the notify/v2 interface for all services
AMRC-FactoryPlus/js-service-api pull request #2
Opened 2024-11-01 14:10 UTC by amrc-benmorrow

Move the implementation of the `notify/v2` interface into this module, so that all F+ services can implement it.

Support SEARCH notify requests.

2024-11-06 16:10 UTC, djnewbould requested changes
Looks good, I've left a few comments. It might be worth adding a few code comments in places especially for some of the RXJS stuff, it can be a little difficult to understand if you're not too familiar with it.

2024-11-06 16:10 UTC, djnewbould commented on lib/notify-v2.js
> +            .filter(s => s.method == "WATCH")
Should we be using `===` here instead of `==`? I think its in a few places.

2024-11-06 16:10 UTC, djnewbould commented on lib/notify-v2.js
> +            rx.flatMap(req => {
My IDE is showing flatMap as being deprecated. https://rxjs.dev/api/operators/flatMap

2024-11-06 16:10 UTC, djnewbould commented on lib/notify-v2.js
> +        return;
Unnecessary return here?

2024-11-06 16:10 UTC, djnewbould commented on package.json
> +  "version": "0.0.2",
Is this version number change correct?

2024-11-07 08:33 UTC, amrc-benmorrow commented on lib/notify-v2.js
> +            .filter(s => s.method == "WATCH")
The `method` key has already been validated by `validate_subscription`, which uses strict equality (`switch` uses strict equality). I would rather validate input initially than have to use `===` all the time; I find it very fussy.

2024-11-07 08:34 UTC, amrc-benmorrow commented on lib/notify-v2.js
> +            rx.flatMap(req => {
:+1:

2024-11-07 08:54 UTC, amrc-benmorrow commented on package.json
> +  "version": "0.0.2",
Yes. The only release so far is `0.0.1`; the GH release process rewrites `package.json` before running `npm publish` so that the published release version matches the git tag. The `1.0.0` came from `npm init` and I forgot to fix it.

2024-11-07 11:13 UTC, djnewbould approved these changes

2024-11-07 11:26 UTC, merged